server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost/libraryBook
    username: root
    password: Dinhphuc2009.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true
  application:
    name: book-service
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka
